name: Manual Build

on:
  workflow_dispatch:
    inputs:
      target_system:
        description: "Target System"
        required: true
        default: ramips

      subtarget:
        description: "Subtarget"
        required: true
        default: mt7620

      sdk_version:
        type: choice
        description: "SDK version"
        options:
          - SNAPSHOT
          - openwrt-23.05
          - openwrt-22.03
        required: true
        default: SNAPSHOT

env:
  PACKAGE_NAME: minieap-gdufs

jobs:
  build:
    name: Build ${{ github.event.inputs.target_system }}-${{ github.event.inputs.subtarget }}-${{ github.event.inputs.sdk_version }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: minieap-gdufs

      - name: Building packages
        uses: openwrt/gh-action-sdk@main
        env:
          TARGET: ${{ github.event.inputs.target_system }}
          SUBTARGET: ${{ github.event.inputs.subtarget }}
          SDK_VERSION: ${{ github.event.inputs.sdk_version }}
          FEED_DIR: ${{ github.workspace }}
          PACKAGES: ${{ env.PACKAGE_NAME }}
          NO_REFRESH_CHECK: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.arch }}-${{ github.event.inputs.sdk_version }}
          path: bin/packages/${{ github.event.inputs.arch }}/action/*.ipk
          retention-days: 7
